#
# Copyright contributors to the Galasa project 
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      name: {{ .Release.Name }}-api
      labels:
        app: {{ .Release.Name }}-api
    spec:
      nodeSelector:
        kubernetes.io/arch: {{ .Values.architecture }}
{{ toYaml .Values.nodeSelectors | indent 8 }}
      initContainers:
      - name: init-chown-data
        image: {{ .Values.galasaRegistry }}/galasa-boot-embedded-{{ .Values.architecture }}:{{ .Values.galasaVersion }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        command: ["chown", "-v", "1000", "/data"]
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: ""
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
      containers:
      - name: api
        image: {{ .Values.galasaRegistry }}/galasa-boot-embedded-{{ .Values.architecture }}:{{ .Values.galasaVersion }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        command: ["java"]
        args: 
        - -jar
        - boot.jar
        - --obr
        - file:galasa.obr
        - --trace
        - --api
        - --bootstrap
        - file:/bootstrap.properties
        env:
        - name: GALASA_CONFIG_STORE
          value: etcd:http://{{ .Release.Name }}-etcd:2379
        - name: GALASA_DYNAMICSTATUS_STORE
          value: etcd:http://{{ .Release.Name }}-etcd:2379
        - name: GALASA_RESULTARCHIVE_STORE
          value: couchdb:http://{{ .Release.Name }}-couchdb:5984
        - name: GALASA_CREDENTIALS_STORE
          value: etcd:http://{{ .Release.Name }}-etcd:2379
        ports:
        - containerPort: 9010
          name: metrics
        - containerPort: 9011
          name: health
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /bootstrap
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: bootstrap
          mountPath: /bootstrap.properties
          subPath: bootstrap.properties
        - name: testcatalog
          mountPath: /galasa/load/dev.galasa.testcatalog.cfg
          subPath: dev.galasa.testcatalog.cfg
        - name: data
          mountPath: /galasa/testcatalog    
      volumes:
      - name: bootstrap
        configMap:
          name: {{ .Release.Name }}-bootstrap-file
      - name: testcatalog
        configMap:
          name: {{ .Release.Name }}-testcatalog-file
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-testcatalog
