#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dex-config
data:
  config.yaml: {{ .Values.dex.config | toYaml | quote }}