#
# Copyright contributors to the Galasa project 
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-engine-controller
  labels:
    app: {{ .Release.Name }}-engine-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-engine-controller
  template:
    metadata:
      name: {{ .Release.Name }}-engine-controller
      labels:
        app: {{ .Release.Name }}-engine-controller
    spec:
      serviceAccountName: galasa
      nodeSelector:
        kubernetes.io/arch: {{ .Values.architecture }}
        {{- if .Values.nodeSelectors }}
{{ toYaml .Values.nodeSelectors | indent 8 }}
        {{- end }}
      containers:
      - name: engine-controller
        image: {{ .Values.galasaRegistry }}/galasa-boot-embedded-{{ .Values.architecture }}:{{ .Values.galasaVersion }}
        imagePullPolicy: Always
        command: ["java"]
        args: 
        - -jar
        - boot.jar
        - --obr
        - file:galasa.obr
        - --trace
        - --k8scontroller
        - --bootstrap
        - http://{{ .Release.Name }}-api:8080/bootstrap
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG
          value: {{ .Release.Name }}-config
        - name: GALASA_CONFIG_STORE
          value: etcd:http://{{ .Release.Name }}-etcd:2379
        - name: GALASA_DYNAMICSTATUS_STORE
          value: etcd:http://{{ .Release.Name }}-etcd:2379
        - name: GALASA_RESULTARCHIVE_STORE
          value: couchdb:http://{{ .Release.Name }}-couchdb:5984
        - name: GALASA_CREDENTIALS_STORE
          value: etcd:http://{{ .Release.Name }}-etcd:2379
        ports:
        - containerPort: 9010
          name: metrics
        - containerPort: 9011
          name: health
        livenessProbe:
          httpGet:
            path: /
            port: 9011
          initialDelaySeconds: 60
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /
            port: 9011
          initialDelaySeconds: 5
          periodSeconds: 10
