{{- if .Values.eventStreamsSecretName }}

{{- $eventStreamsSecretName := (printf "%s-%s" .Release.Name .Values.eventStreamsSecretName) }}

{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $eventStreamsSecretName) }}

{{- if not $existingSecret }}

{{- $token := randAlphaNum 44 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $eventStreamsSecretName }}
type: Opaque
stringData:
  GALASA_EVENT_STREAMS_TOKEN: "{{ $token }}"

{{- end -}}

{{- end }}