# eventStreamsSecretName set in values.yaml so use that Secret name for the lookup
{{- if .Values.eventStreamsSecretName }}

{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.eventStreamsSecretName) }}

{{- if not $existingSecret }}

{{- $eventStreamsSecretName := (printf "%s-%s" .Release.Name "event-streams-token") }}
{{- $token := randAlphaNum 44 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $eventStreamsSecretName }}
type: Opaque
stringData:
  GALASA_EVENT_STREAMS_TOKEN: "{{ $token }}"

{{- end -}}

# eventStreamsSecretName not set in values.yaml so generate a name and a Secret
{{- else }}

{{- $eventStreamsSecretName := (printf "%s-%s" .Release.Name "event-streams-token") }}
{{- $token := randAlphaNum 44 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $eventStreamsSecretName }}
type: Opaque
stringData:
  GALASA_EVENT_STREAMS_TOKEN: "{{ $token }}"

{{- end }}