#
# Copyright contributors to the Galasa project 
#
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-setup"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{ .Release.Name }}-post"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      nodeSelector:
        kubernetes.io/arch: {{ .Values.architecture }}
{{ toYaml .Values.nodeSelectors | indent 8 }}
      restartPolicy: Never
      serviceAccountName: galasa
      containers:
      - name: post-install
        image: {{ .Values.galasaRegistry }}/galasa-boot-embedded-amd64:{{ .Values.galasaVersion }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        command: ["/galasa/helm-post-install.sh"]
        args: 
        - {{ .Values.externalHostname }}
        - {{ .Release.Name }}-
        env:
        - name: GALASA_CONFIG_STORE
          value: etcd:http://{{ .Release.Name }}-etcd:2379
        - name: GALASA_DYNAMICSTATUS_STORE
          value: etcd:http://{{ .Release.Name }}-etcd:2379
        - name: GALASA_RESULTARCHIVE_STORE
          value: couchdb:http://{{ .Release.Name }}-couchdb:5984
        - name: GALASA_CREDENTIALS_STORE
          value: etcd:http://{{ .Release.Name }}-etcd:2379
