#
# Copyright contributors to the Galasa project 
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc-testcatalog
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.catalogDiskSize }}
