apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        longhorn: "true"
        tekton: build
      containers:
      - name: api
        image: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-ibm-boot-embedded-amd64:iss990
        imagePullPolicy: Always
        command: ["java"]
        args: 
        - -jar
        - boot.jar
        - --obr
        - file:galasa.obr
        - --trace
        - --api
        - --bootstrap
        - file:/bootstrap.properties
        env:
        - name: GALASA_CONFIG_STORE
          value: etcd:http://etcd:2379
        - name: GALASA_DYNAMICSTATUS_STORE
          value: etcd:http://etcd:2379
        - name: GALASA_RESULTARCHIVE_STORE
          value: couchdb:http://couchdb:5984
        - name: GALASA_CREDENTIALS_STORE
          value: etcd:http://etcd:2379
        ports:
        - containerPort: 9010
          name: metrics
        - containerPort: 9011
          name: health
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /bootstrap
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: bootstrap
          mountPath: /bootstrap.properties
          subPath: bootstrap.properties
        - name: testcatalog
          mountPath: /galasa/load/dev.galasa.testcatalog.cfg
          subPath: dev.galasa.testcatalog.cfg
        - name: data
          mountPath: /galasa/testcatalog    
      volumes:
      - name: bootstrap
        configMap:
          name: bootstrap-file
      - name: testcatalog
        configMap:
          name: testcatalog-file
      - name: data
        persistentVolumeClaim:
          claimName: pvc-testcatalog
