apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-ras
  labels:
    name: {{ .Release.Name }}-ras
spec:
  serviceName: {{ .Release.Name }}-ras
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ras
  template:
    metadata:
      name: {{ .Release.Name }}-ras
      labels:
        app: {{ .Release.Name }}-ras
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        longhorn: "true"
        tekton: build
      containers:
      - name: couchdb
        image: docker.galasa.dev/couchdb:2.3.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5984
          name: couchdbport
        - containerPort: 4369
          name: erlangbport
        - containerPort: 9100
        livenessProbe:
          httpGet:
            path: /
            port: 5984
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
        - mountPath: /opt/couchdb/data
          name: data
      volumes:
      - name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: "longhorn-temp"
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 10Gi
