#
# Copyright contributors to the Galasa project 
#
apiVersion: v1
kind: Service
metadata:
  name: engine-controller-external
  labels:
    app: engine-controller
spec:
  ports:
  - port: 9010
    name: metrics
  - port: 9011
    name: health
  selector:
    app: engine-controller
