apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc-testcatalog
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  storageClassName: "longhorn-temp"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
