apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-testcatalog
spec:
  storageClassName: "longhorn-temp"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
