name: Trigger Helm workflow in automation repository

on:
  push:
    branches: [main]
  
env:
  NAMESPACE: jaydee029

permissions: write-all

jobs:
    trigger-workflow:
        name: trigger helm workflow
        runs-on: ubuntu-latest

        steps:
        - name: Triggering workflow using Github API call
          run: |
           gh api \
           --method POST \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           /repos/${{env.NAMESPACE}}/automation/actions/workflows/build-helm.yaml/dispatches \
           -f "ref=main"
          
          env:
            GH_TOKEN: ${{ github.token }}

