name: Trigger Helm workflow in automation repository

on:
  push:
    branches: [main]
  
env:
  NAMESPACE: jaydee029

jobs:
    trigger-workflow:
        name: trigger helm workflow
        runs-on: ubuntu-latest

        steps:
        - name: Triggering workflow using Github API call
          run: |
            curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{github.token}}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/${{env.NAMESPACE}}/automation/actions/workflows/build-helm.yaml/dispatches  -d '{"ref":"main","inputs":{}}'
          

