name: Trigger Helm workflow in automation repository

on:
  push:
    branches: [main]

jobs:
    trigger-workflow:
        name: trigger helm workflow
        runs-on: ubuntu-latest

        steps:
        - name: Triggering workflow
          uses: convictional/trigger-workflow-and-wait@v1.6.1
          with:
            owner: jaydee029
            repo: automation
            github_token: ${{ secrets.GITHUB_TOKEN }}
            workflow_file_name: build-helm.yaml
            trigger_workflow: true
            wait_workflow: true

