#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Release Charts

on:
  push:
    branches:
      - prerelease
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        if: (github.ref == 'refs/heads/prerelease')
        uses: helm/chart-releaser-action@main
        with: 
          skip_existing: true
          skip_packaging: true
          skip_upload: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        if: (github.ref == 'refs/heads/release')
        uses: helm/chart-releaser-action@main
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"